services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ayaan
    volumes:
      - pgdata:/var/lib/postgresql/data 
    network_mode: "host"
    ports:
      - 5432:5432
 
volumes:
  pgdata: